pretraining:
  progress:
    total_safetensors: 252
    completed_safetensors: "1-15"
    completion_percentage: 13
    last_checkpoint: "model-00001-to-00015-of-00252.safetensors"
    validation_status: "completed"
    test_status: "completed"

monitoring:
  checkpoints:
    save_frequency: "per_safetensor"
    validate_after_each: true
    test_after_each: true

continuation:
  next_batch: "model-00016-to-00030-of-00252.safetensors"
  resume_from: "model-00001-to-00015-of-00252.safetensors"
