name: vishwamai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - cudatoolkit=11.8
  - pytorch=2.1.0
  - torchvision=0.16.0
  - numpy>=1.24.0
  - pandas>=2.1.0
  - pip:
    # Core ML
    - transformers==4.34.0
    - accelerate==0.27.0
    - bitsandbytes>=0.41.1
    - deepspeed==0.12.3
    - datasets==2.16.1
    - apache-tvm==0.14.0
    - onnx==1.15.0
    - onnxruntime-gpu==1.16.3
    
    # Optimization and Security
    - intel-sgx-ra==1.0.0
    - cryptography==41.0.7
    - stable-baselines3==2.1.0
    
    # Monitoring and Metrics
    - wandb==0.16.2
    - tensorboard==2.15.1
    - prometheus-client==0.19.0
    - grafana-api==1.0.3
    - opentelemetry-api==1.21.0
    - opentelemetry-sdk==1.21.0
    - opentelemetry-instrumentation-fastapi==0.42b0
    
    # Web Serving
    - fastapi==0.109.0
    - "uvicorn[standard]==0.27.0.post1"
    - python-multipart==0.0.6
    - pydantic==2.6.1
    - starlette==0.36.3
    - websockets==12.0
    
    # Development
    - pytest>=7.4.0
    - pytest-asyncio>=0.23.0
    - hypothesis>=6.98.0
    - black>=23.12.1
    - isort>=5.13.2
    - mypy>=1.8.0
    
    # Documentation
    - sphinx>=7.1.0
    - sphinx-rtd-theme>=2.0.0

variables:
  CUDA_HOME: /usr/local/cuda
  LD_LIBRARY_PATH: /usr/local/cuda/lib64:$LD_LIBRARY_PATH
  NVIDIA_VISIBLE_DEVICES: all
