# Data configuration

# Tokenizer settings
tokenizer:
  vocab_size: 32000
  model_type: sentencepiece
  special_tokens:
    pad_token: "[PAD]"
    unk_token: "[UNK]"
    bos_token: "[BOS]"
    eos_token: "[EOS]"
    mask_token: "[MASK]"
  training:
    input_sentence_size: 10000000
    shuffle_input_sentence: true
    character_coverage: 0.9995
    model_type: bpe
    split_digits: false
    split_by_whitespace: true
    treat_whitespace_as_suffix: false
    control_symbols: []
    user_defined_symbols: []
    required_chars: ""
    byte_fallback: true

# Data preprocessing
preprocessing:
  text_cleaning:
    remove_html: true
    normalize_unicode: true
    remove_extra_whitespace: true
    fix_unicode: true
    standardize_punctuation: true
  tokenization:
    add_special_tokens: true
    truncation: true
    max_length: 2048
    padding: max_length
    return_attention_mask: true
    return_token_type_ids: false
  augmentation:
    enabled: false
    methods:
      - random_deletion
      - random_swap
      - back_translation
    probability: 0.1
    max_augmentations: 2

# Dataset configurations
datasets:
  pretrain:
    paths:
      - data/books
      - data/wiki
      - data/stackoverflow
      - data/github
    sampling_weights: [0.3, 0.3, 0.2, 0.2]
    streaming: true
    shuffle_buffer_size: 10000
    cache: true
    
  mmlu:
    path: data/mmlu
    use_few_shot: true
    num_shots: 5
    subjects:
      - stem
      - humanities
      - social_sciences
      - other
    eval_split: dev
    metrics:
      - accuracy
      - subject_accuracy
      
  mmmu:
    path: data/mmmu
    use_multimodal: true
    image_size: 224
    patch_size: 16
    max_image_tokens: 256
    metrics:
      - accuracy
      - vqa_score
      
  gsm8k:
    path: data/gsm8k
    use_chain_of_thought: true
    max_steps: 8
    include_rationale: true
    metrics:
      - exact_match
      - step_accuracy

# Dataloader settings
dataloader:
  batch_size: 32
  num_workers: 4
  prefetch_factor: 2
  persistent_workers: true
  pin_memory: true
  drop_last: true
  shuffle: true
  sampler:
    type: weighted
    replacement: true
    num_samples: null

# Caching and storage
storage:
  cache_dir: .cache
  max_cached_samples: 100000
  cache_format: mmap
  compression: none
  cleanup_on_exit: true
  storage_options:
    anon: true
    protocol: gs
    project: null

# Data quality filters
filters:
  min_length: 10
  max_length: 100000
  min_words: 3
  max_words: 20000
  language: en
  remove_duplicate_lines: true
  similarity_threshold: 0.85
  min_unique_tokens: 5
  max_repeated_phrases: 10

# Validation settings
validation:
  split_ratio: 0.05
  stratify: true
  random_state: 42
  validation_frequency: 1000
  eval_batch_size: 64
  max_validation_steps: 100
  validation_metrics:
    - perplexity
    - accuracy
    - loss

# Monitoring
monitoring:
  log_data_stats: true
  profile_dataloaders: true
  track_samples_per_second: true
  data_quality_alerts: true
  max_logged_samples: 10
  monitor_memory_usage: true
  alert_on_skew: true
  save_bad_samples: true
