global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'vishwamai'
    static_configs:
      - targets: ['vishwamai:8000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'model_metrics'
    static_configs:
      - targets: ['vishwamai:9090']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'gpu_metrics'
    static_configs:
      - targets: ['dcgm-exporter:9400']

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

rule_files:
  - "alert_rules.yml"
