global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'vishwamai'
    static_configs:
      - targets: ['vishwamai:8000']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 5s  # Faster scraping for core metrics
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'expert_.*'
        action: keep

  - job_name: 'model_metrics'
    static_configs:
      - targets: ['vishwamai:9090']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 10s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(moe_|token_routing_|cache_).*'
        action: keep

  - job_name: 'expert_metrics'
    static_configs:
      - targets: ['vishwamai:9091']
    metrics_path: '/moe/metrics'
    scheme: 'http'
    scrape_interval: 5s
    metric_relabel_configs:
      - source_labels: [expert_id]
        target_label: expert
        regex: '(.+)'

  - job_name: 'memory_metrics'
    static_configs:
      - targets: ['vishwamai:9092']
    metrics_path: '/memory/metrics'
    scheme: 'http'
    scrape_interval: 10s

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  - job_name: 'gpu_metrics'
    static_configs:
      - targets: ['dcgm-exporter:9400']
    scrape_interval: 5s
    metric_relabel_configs:
      - source_labels: [gpu]
        target_label: gpu_id
        regex: 'GPU-(.+)'
      - source_labels: [__name__]
        regex: 'DCGM_FI_DEV_.*'
        action: keep

  - job_name: 'kv_cache_metrics'
    static_configs:
      - targets: ['vishwamai:9093']
    metrics_path: '/cache/metrics'
    scheme: 'http'
    scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      scheme: 'http'
      timeout: 10s
      api_version: v2

rule_files:
  - "alert_rules.yml"
