name: Python package

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        environment: [cpu, gpu]
    runs-on: ${{ matrix.environment == 'gpu' && 'self-hosted, gpu, ubuntu-latest' || 'ubuntu-latest' }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch
        pip install -r requirements.txt
    
    - name: Install pytest and transformers
      run: |
        pip install pytest
        pip install transformers datasets
    
    - name: Set up PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Configure Hugging Face Token
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        mkdir -p ~/.huggingface
        echo "{ \"token\": \"${HF_TOKEN}\" }" > ~/.huggingface/token
        chmod 600 ~/.huggingface/token

    - name: Run tests with pytest
      run: pytest
